"""
Ω宇宙系统 — 22系统完全融合
"""
from .omega_system import (
    ΩLevel, ΩNumber,
    AbilityType, Ability, AbilityMatrix,
    MetaAbility, SuperpowerSystem,
    MindNode, SuperBrainSystem,
    AugmentationSystem,
    ImmortalitySystem,
    TalentMutationSystem,
    CapitalPredatorEngine,
    CoreSystemsCoordinator,
    TimelineNode, CausalChain, SpacetimeControlSystem,
    MultidimensionalConsciousnessSystem,
    DestinyInterferenceSystem,
    RealityCreationSystem,
    QuantumAdvantageSystem,
    EnergyMasterySystem,
    OmniscienceDataSystem,
    SuperAlgorithmSystem,
    ExtendedSystemsCoordinator,
    MemoryUniverseSystem,
    InfluencePenetrationSystem,
    CollectiveEvolutionSystem,
    InfiniteResourceSystem,
    DivineTotalitySystem,
    CosmicConsciousnessSystem,
    MetaEvolutionSystem,
    OmegaUnifiedCoordinator,
    main as omega_main,
)

__all__ = [
    "ΩLevel", "ΩNumber",
    "AbilityType", "Ability", "AbilityMatrix",
    "MetaAbility", "SuperpowerSystem",
    "MindNode", "SuperBrainSystem",
    "AugmentationSystem",
    "ImmortalitySystem",
    "TalentMutationSystem",
    "CapitalPredatorEngine",
    "CoreSystemsCoordinator",
    "SpacetimeControlSystem",
    "MultidimensionalConsciousnessSystem",
    "DestinyInterferenceSystem",
    "RealityCreationSystem",
    "QuantumAdvantageSystem",
    "EnergyMasterySystem",
    "OmniscienceDataSystem",
    "SuperAlgorithmSystem",
    "ExtendedSystemsCoordinator",
    "MemoryUniverseSystem",
    "InfluencePenetrationSystem",
    "CollectiveEvolutionSystem",
    "InfiniteResourceSystem",
    "DivineTotalitySystem",
    "CosmicConsciousnessSystem",
    "MetaEvolutionSystem",
    "OmegaUnifiedCoordinator",
]
