"""
Ω宇宙系统 — 22系統完全融合

核心系統 S01-S07 | 擴展系統 S08-S15 | 頂層系統 S16-S22
"""
from .omega_system import (
    ΩLevel,
    ΩNumber,
    AbilityType,
    Ability,
    AbilityMatrix,
    MetaAbility,
    SuperpowerSystem,
    MindNode,
    SuperBrainSystem,
    AugmentationSystem,
    ImmortalitySystem,
    TalentMutationSystem,
    CapitalPredatorEngine,
    CoreSystemsCoordinator,
    SpacetimeControlSystem,
    MultidimensionalConsciousnessSystem,
    DestinyInterferenceSystem,
    RealityCreationSystem,
    QuantumAdvantageSystem,
    EnergyMasterySystem,
    OmniscienceDataSystem,
    SuperAlgorithmSystem,
    ExtendedSystemsCoordinator,
    MemoryUniverseSystem,
    InfluencePenetrationSystem,
    CollectiveEvolutionSystem,
    InfiniteResourceSystem,
    DivineTotalitySystem,
    CosmicConsciousnessSystem,
    MetaEvolutionSystem,
    OmegaUnifiedCoordinator,
    main as omega_main,
)

__all__ = [
    "ΩLevel",
    "ΩNumber",
    "AbilityType",
    "Ability",
    "AbilityMatrix",
    "MetaAbility",
    "SuperpowerSystem",
    "MindNode",
    "SuperBrainSystem",
    "AugmentationSystem",
    "ImmortalitySystem",
    "TalentMutationSystem",
    "CapitalPredatorEngine",
    "CoreSystemsCoordinator",
    "SpacetimeControlSystem",
    "MultidimensionalConsciousnessSystem",
    "DestinyInterferenceSystem",
    "RealityCreationSystem",
    "QuantumAdvantageSystem",
    "EnergyMasterySystem",
    "OmniscienceDataSystem",
    "SuperAlgorithmSystem",
    "ExtendedSystemsCoordinator",
    "MemoryUniverseSystem",
    "InfluencePenetrationSystem",
    "CollectiveEvolutionSystem",
    "InfiniteResourceSystem",
    "DivineTotalitySystem",
    "CosmicConsciousnessSystem",
    "MetaEvolutionSystem",
    "OmegaUnifiedCoordinator",
    "omega_main",
]
